
package com.bidServ.model.view.post;

import oracle.jbo.CriteriaAdapter;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 25 16:22:31 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntireNetworkPostVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EntireNetworkPostVOImpl() {
    }
    private static CriteriaAdapter postCriteriaAdaptor = new PostCriteriaAdaptor();
    public CriteriaAdapter getCriteriaAdapter(){
        return postCriteriaAdaptor;
    }
}

