package com.bidServ.model.view.post;

import java.math.BigDecimal;

import oracle.jbo.CriteriaAdapter;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 29 00:12:25 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrimaryConnPostVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PrimaryConnPostVOImpl() {
    }
    
    private static CriteriaAdapter postCriteriaAdaptor = new PostCriteriaAdaptor();
    public CriteriaAdapter getCriteriaAdapter(){
        return postCriteriaAdaptor;
    }
}

