package com.bidServ.model.applicationModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 20 23:18:00 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BidServAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BidServAMImpl() {
    }

    /**
     * Container's getter for PostVO1.
     * @return PostVO1
     */
    public ViewObjectImpl getPostVO1() {
        return (ViewObjectImpl) findViewObject("PostVO1");
    }
    
    public void executeMemberPost(String vcName){
        ViewObjectImpl postVO = getPostVO1();
        postVO.applyViewCriteria(null);
        postVO.setApplyViewCriteriaName(vcName);
    }
}

