package com.bidServ.model.applicationModule;

import com.bidServ.model.applicationModule.common.BidServAM;
import com.bidServ.model.view.post.EntireNetworkPostVOImpl;
import com.bidServ.model.view.post.PrimaryConnPostVOImpl;
import com.bidServ.model.view.post.SecondaryConnPostVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 29 13:27:24 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BidServAMImpl extends ApplicationModuleImpl implements BidServAM {
    /**
     * This is the default constructor (do not remove).
     */
    public BidServAMImpl() {
    }

    /**
     * Container's getter for PostVO1.
     * @return PostVO1
     */
    public ViewObjectImpl getPostVO1() {
        return (ViewObjectImpl) findViewObject("PostVO1");
    }

    /**
     * Container's getter for createPostVO.
     * @return createPostVO
     */
    public ViewObjectImpl getcreatePostVO() {
        return (ViewObjectImpl) findViewObject("createPostVO");
    }

    /**
     * Container's getter for SupplierNetworkVO.
     * @return SupplierNetworkVO
     */
    public EntireNetworkPostVOImpl getSupplierNetworkVO() {
        return (EntireNetworkPostVOImpl) findViewObject("SupplierNetworkVO");
    }

    /**
     * Container's getter for SecondaryConnVO.
     * @return SecondaryConnVO
     */
    public SecondaryConnPostVOImpl getSecondaryConnVO() {
        return (SecondaryConnPostVOImpl) findViewObject("SecondaryConnVO");
    }

    /**
     * Container's getter for PrimaryConnVO.
     * @return PrimaryConnVO
     */
    public PrimaryConnPostVOImpl getPrimaryConnVO() {
        return (PrimaryConnPostVOImpl) findViewObject("PrimaryConnVO");
    }
    
    public void searchPost(String voName, String keyword){
        ViewObjectImpl vo = null;
        if(voName.equals("E")){
            vo = getSupplierNetworkVO();
        }else if(voName.equals("S")){
            vo = getSecondaryConnVO();
        }else if(voName.equals("P")){
            vo = getPrimaryConnVO();
        }
        if(vo != null){
            if (keyword == null || keyword.length()==0){
                vo.removeApplyViewCriteriaName("SearchVC");
            }else{
                vo.setApplyViewCriteriaName("SearchVC",true);
                vo.setNamedWhereClauseParam("keyword", keyword);
            }
             vo.executeQuery();
        }
    }    
}

