package com.bidServ.model.view.common;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 17 15:15:15 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoggedInUserVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserId,
        Name,
        CompanyId,
        CompanyName,
        LogoURL,
        IsAdmin,
        Status;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return LoggedInUserVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return LoggedInUserVORowImpl.AttributesEnum.firstIndex() +
                   LoggedInUserVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = LoggedInUserVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERID = AttributesEnum.UserId.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int LOGOURL = AttributesEnum.LogoURL.index();
    public static final int ISADMIN = AttributesEnum.IsAdmin.index();
    public static final int STATUS = AttributesEnum.Status.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LoggedInUserVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public Long getUserId() {
        return (Long) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserId.
     * @param value value to set the  UserId
     */
    public void setUserId(Long value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name.
     * @param value value to set the  Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyId.
     * @return the CompanyId
     */
    public Long getCompanyId() {
        return (Long) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompanyId.
     * @param value value to set the  CompanyId
     */
    public void setCompanyId(Long value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyName.
     * @return the CompanyName
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompanyName.
     * @param value value to set the  CompanyName
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LogoURL.
     * @return the LogoURL
     */
    public String getLogoURL() {
        return (String) getAttributeInternal(LOGOURL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LogoURL.
     * @param value value to set the  LogoURL
     */
    public void setLogoURL(String value) {
        setAttributeInternal(LOGOURL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsAdmin.
     * @return the IsAdmin
     */
    public String getIsAdmin() {
        return (String) getAttributeInternal(ISADMIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsAdmin.
     * @param value value to set the  IsAdmin
     */
    public void setIsAdmin(String value) {
        setAttributeInternal(ISADMIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }
}

