package com.bidServ.model.applicationModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 25 16:15:06 IST 2016
// ---------------------------------------------------------------------
public interface BidServAM extends ApplicationModule {
    void searchPost(String voName, String keyword);
}

