package com.bidServ.model.applicationModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 29 13:28:02 IST 2016
// ---------------------------------------------------------------------
public interface BidServAM extends ApplicationModule {
    void searchPost(String voName, String keyword);
}

