package com.bidServ.model.applicationModule.common;

import java.math.BigDecimal;

import java.util.ArrayList;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 29 13:28:02 IST 2016
// ---------------------------------------------------------------------
public interface BidServAM extends ApplicationModule {
    void searchPost(String voName, String keyword);

    void setMyPostVC(BigDecimal userId);

    void setMyBidsVC(BigDecimal userId);

    void postDetails(String source, String userId, String postId);

    void createComment(int bidId, int userId, String username, String comment);

    Long initLoggedInUser();

    Long initCompany();

    void createPostRow();

    void initChatforBid(Long bindBidId);

    void deleteNewCompanay();

    Long initLoggedInUser(String username);

    void loadAdminData();

    void createNewUser(String invId, String email);

    void queryUser(Long userId);

    void searchCompany(String name);

    String createConnection(ArrayList keys);

    void updateConnectionRequest(BigDecimal connectionId, String responseCode);

    void updateUserRequest(BigDecimal userId, String actionCode);

    void createBid(String desc, String amt);

    void grantBid(BigDecimal bidId);

    void sendInvites(String emailList);

    String validateRegistration(String code, String email);

    void invitationAccepted(String code, String email);

    void completeVerificationRequest(int requestId, String outcome);

    void requestVerification();

    void reportCompany(int companyId);

    void reportUser(int userId);

    void handlReportedEntity(String type, int id, String outcome);

    void createAttachment(String type, int id, String url, String name);

    void setBidRow(BigDecimal bidId);

    void editBid(String desc, String amt);

    Long initLoggedInUser(String username, String enteredPassword);

    boolean storePassword(String password);
}

