package com.bidServ.model.view.setup;

import com.bidServ.model.view.post.PostCriteriaAdaptor;

import java.math.BigDecimal;

import oracle.jbo.CriteriaAdapter;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 26 13:04:24 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CompanyVOImpl() {
    }


    private static CriteriaAdapter companyCriteriaAdaptor = new CompanyCriteriaAdaptor();
    public CriteriaAdapter getCriteriaAdapter(){
        return companyCriteriaAdaptor;
    }
}

